CREATE TABLE "levels" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "name" text NOT NULL,
  "message" text,
  "structure" jsonb NOT NULL
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "icon" bytea,
  "email" text NOT NULL,
  "username" text NOT NULL,
  "password" text NOT NULL,
  "role" text NOT NULL
);

ALTER TABLE "levels" ADD FOREIGN KEY ("id") REFERENCES "users" ("id");
